name: pytest

on: [ push ]

env:
  BUILD_OUTPUT: build/_libs/libbitcoinkernel.so

jobs:
  build-bitcoinkernel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Restore bitcoinkernel from cache
        id: cache-lib
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.BUILD_OUTPUT }}
          key: pytest-bitcoinkernel-${{ runner.os }}-${{ hashFiles('depend/bitcoin/**', 'CMakeLists.txt') }}

      - name: Install build dependencies
        if: steps.cache-lib.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-dev
      
      - name: Build bitcoinkernel library
        if: steps.cache-lib.outputs.cache-hit != 'true'
        run: |
          cmake -B build
          cmake --build build -j
          cmake --install build --prefix build/_libs/

      - name: Save lib cache
        if: steps.cache-lib.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ${{ env.BUILD_OUTPUT }}
          key: ${{ steps.cache-lib.outputs.cache-primary-key}}

  test:
    needs: build-bitcoinkernel
    runs-on: ubuntu-latest
    if: ${{ success() || needs.build-bitcoinkernel.result == 'skipped' }}  # Run if build succeeds or is skipped
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Restore bitcoinkernel from cache
        id: cache-lib
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.BUILD_OUTPUT }}
          key: pytest-bitcoinkernel-${{ runner.os }}-${{ hashFiles('depend/bitcoin/**', 'CMakeLists.txt') }}

      - name: Install dependencies
        env:
          BITCOINKERNEL_LIB: ${{ env.BUILD_OUTPUT }}
        run: |
          pip install ".[test]"

      - name: Run tests with pytest
        run: |
          pytest
